export const LABELS: Record<string, string> = {
  date: 'Дата',
  role: 'Автор документа',
  purchase_date: 'Дата покупки',
  buyer: 'Данные покупателя',
  seller: 'Данные продавца',
  price: 'Цена',
  sum_rub: 'Сумма в рублях',
  subject: 'Субъект договора',
  automobile: 'Автомобиль',
  number: 'Номер договора',
  VIN: 'VIN автомобиля',
  city: 'Город',
  registration_address: 'Адрес регистрации',
  registration_address_seller: 'Адрес регистрации продавца',
  registration_address_buyer: 'Адрес регистрации покупателя',
  passport_info: 'Паспортные данные',
  passport_info_seller: 'Паспортные данные продавца',
  passport_info_buyer: 'Паспортные данные покупателя',
  address: 'Адрес',
  subject_item_year: 'Год выпуска предмета',
  automobile_probeg: 'Пробег автомобиля',
  automobile_color: 'Цвет автомобиля',
  automobile_marka: 'Марка автомобиля',
  automobile_model: 'Модель автомобиля',
  count_of_deal: 'Количество договоров',
  obligations_of_deal: 'Обязательства по договору',
  transfer_act: 'Акт передачи',
  risk_transfer: 'Перенос риска',
  warranty: 'Гарантия',
  amendments: 'Изменения и дополнения',
  division: 'Подразделение',
  organization_name: 'Название организации',
  INN: 'ИНН',
  OGRN: 'ОГРН',
  legal_address: 'Юридический адрес',
  registration_date: 'Дата регистрации',
  to_role: 'Роль получателя',
  to_company: 'Компания получателя',
  to_fio: 'ФИО получателя',
  to_address: 'Адрес получателя',
  disctrict: 'Район (опечатка)',
  district: 'Район',
  dealNumber: 'Номер дела',
  startDate: 'Дата начала',
  currentDate: 'Текущая дата',
  accusedFio: 'ФИО обвиняемого',
  hour: 'Час',
  minutes: 'Минуты',
  year: 'Год',
  time: 'Время',
  podNumber: 'Номер подъезда',
  homeNumber: 'Номер дома',
  streetName: 'Название улицы',
  street: 'Улица',
  victimFullName: 'ФИО жертвы',
  hospitalNumber: 'Номер больницы',
  doctorReview: 'Заключение врача',
  docturReviewNumber: 'Номер заключения врача',
  doctorReviewDate: 'Дата заключения врача',
  doctorReviewFull: 'Полное заключение врача',
  MRSOName: 'Название МРСО',
  MRSODeal: 'Номер дела в МРСО',
  contract_number: 'Номер договора',
  contract_date: 'Дата договора',
  borrower: 'Заемщик',
  pawnshop: 'Ломбард',
  loan_amount: 'Сумма займа',
  interest_rate: 'Процент займа',
  collateral_item: 'Предмет залога',
  collateral_value: 'Стоимость залога',
  redemption_date: 'Дата выкупа',
  borrower_address: 'Адрес заемщика',
  borrower_passport_info: 'Паспортные данные заемщика',
  pawnshop_address: 'Адрес ломбарда',
  pawnshop_registration_info: 'Регистрационная информация ломбарда',
  buyer_company: 'Компания покупателя',
  buyer_director: 'Генеральный директор покупателя',
  buyer_address: 'Адрес покупателя',
  buyer_inn: 'ИНН покупателя',
  seller_company: 'Компания поставщика',
  seller_director: 'Генеральный директор поставщика',
  seller_address: 'Адрес поставщика',
  seller_inn: 'ИНН поставщика',
  product_name: 'Наименование продукции',
  product_quantity: 'Количество продукции',
  product_price: 'Цена продукции',
  total_price: 'Общая стоимость продукции',
  delivery_schedule: 'График поставок',
  payment_terms: 'Условия оплаты',
  warranty_period: 'Гарантийный срок',
  arbitration_location: 'Место разрешения споров',
  prosecutorFio: 'ФИО прокурора',
};
